<?php

include("fpdf.php");
include('session.php');


$token = $_GET["token"];


$notify = $workercomments->getDocument($token);


//PDF Generator

class PDF extends FPDF
{
function Header()
{
    // Select Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(20);
    // Framed title
    $this->Cell(150,10,'Cleaning Report for '.date('F, Y')." ",1,0,'C');
    // Line break
    $this->Ln(25);
}

function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'This is autogenerated and signature is not needed',0,0,'C');
}
}


ob_start();
$pdf = new PDF();
$pdf->AddPage();
//Set Border Colour
$pdf->SetDrawColor(220 ,220,220);
$pdf->SetFont('Arial','',10);


$pdf->Cell(38,6,"Time Issued",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["time"],1,0,'L');
// Line break
$pdf->Ln(7);

$pdf->Cell(38,6,"Report ID",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["NotID"],1,0,'L');
// Line break
$pdf->Ln(7);

//Accepted On
$pdf->Cell(38,6,"Accepted On",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["accepted_on"],1,0,'L');
// Line break
$pdf->Ln(7);

//Accepted By
$pdf->Cell(38,6,"Accepted By",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["accepted_by"],1,0,'L');
// Line break
$pdf->Ln(7);

//Comments
$pdf->Cell(38,6,"Comments",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["comments"],1,0,'L');
// Line break
$pdf->Ln(7);

//Message
$pdf->Cell(38,6,"Message",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["message"],1,0,'L');
// Line break
$pdf->Ln(7);

//Rating 
$pdf->Cell(38,6,"Rating",1,0,'L');
$pdf->Cell(3,8,'',0); //cell without borders
$pdf->Cell(140,6,$notify["rating"],1,0,'L');
// Line break
$pdf->Ln(10);

//Images
$pdf->Image($notify["image_url"],60,100,90,0,'jpg');
// Line break
$pdf->Ln(7);

// Line break
$pdf->Ln(7);

//Output PDF
$pdf->Output('D',$notify["NotID"].".pdf",'false');
ob_end_flush(); 


?>

























?>